### PR TITLE
Update instructions to add model creation header

### PR DESCRIPTION
**Pull request by timani**
The first step is to create a model but the first header is "Create a Book Repository" which is the second step

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@timani Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-caching&pullRequestId=16)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-caching&pullRequestId=16) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@timani Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-caching&pullRequestId=16)!

**Comment by Buzzardo** [comment]
Thanks for catching that. It's simple enough that I merged it without the CLA being signed.

**Comment by timani** [comment]
thanks @Buzzardo! First Spring contribution so happy to provide the help where possible

**Pull request merged**
