### PR TITLE
Updated for cache auto-configuration

### PR DESCRIPTION
**Pull request by Bert-R**
Removed the explicit cache manager bean and updated the guide accordingly.

### CODE REVIEW

**Comment by gregturn** [comment]
Looks great. 

Can you drop the "Since version 3.1" clause? We don't need to drag along new vs old Boot behavior. 

Have you signed the CLA?

**Comment by Bert-R** [comment]
I've removed that now.
Yes, I have signed the ICLA

**Comment by gregturn** [comment]
Looks perfect. If I could trouble you to squash that, I'll merge it.

**Comment by Bert-R** [comment]
I'm quite new to Git, so I'm not entirely sure whether I did it right.

**Comment by gregturn** [comment]
git rebase -i master

Mark every commit, except the first, as "s" for squash. You'll have an interactive opportunity to polish the final commit message. Then "git push --force" to your branch. 

Read this for more details. http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by Bert-R** [comment]
Thanks. I missed the --force at first, so did a pull and created a mess.

**Comment by gregturn** [comment]
Perfect!

**Pull request merged**
